gosling-lang/gos

- example/composite_vis/comparative_matrices.py
Micro-c data was duplicated originally.
> fix: display micro-c and hi-c data in matrix example

- gosling/api.py
- gosling/schema/mixins.py
- tools/generate_schema_wrapper.py
Right now the mixin methods obfuscate the type (which should be the same as `self`). This PR adds a generic type parameter to self for the mixin methods so that the return type can be inferred.
```python
import gosling as gos
track = gos.Track(...) # track is type `Track`
track = gos.Track(...).mark_brush() # track is type `Unknown`
track = gos.Track(...).mark_brush().encode(...) # track is type `Unknown`
```
```python
import gosling as gos
track = gos.Track(...) # track is type `Track`
track = gos.Track(...).mark_brush() # track is type `Track`
track = gos.Track(...).mark_brush().encode(...) # track is type `Track`
```
> feat: infer mixin return type

- example/overview_detail.py
- example/routes.json
Adds [Overview + Detail](https://gosling.js.org/?example=CIRCULAR_OVERVIEW_LINEAR_DETAIL) example.
> feat: add circular overview + detail example

- example/genes.py
- example/multiscale-lolipop-plot.py
- example/multiscale-lollipop-plot.py
- example/multiscale_sequence.py
- gosling/api.py
- gosling/tests/test_api.py
- gosling/tests/test_data.py
- gosling/utils/core.py
Implements #34
I chose to use the corresponding aliases (`le` & `ge` instead of `ltet` and `gtet`) since these names correspond with python built-in dunder methods: https://docs.python.org/3/reference/datamodel.html#object.__lt__
> feat: add `.visibility_{lt,gt,le,ge}` mixin methods

- gosling/__init__.py
- gosling/display.py
- gosling/experimental/_provider.py
- gosling/experimental/data.py
- gosling/experimental/tests/test_data_server.py
Requires that `gosling.[dev]` for installation. If we can support this feature without the data-server (using the json data-type), but this would currently lead to embedding the full dataset multiple times in the chart definition becaused we don't support data references: https://github.com/gosling-lang/gosling.js/issues/508
```python
import gosling as gos # import registers `pd.Dataframe.gos` namespace
import pandas as pd
df = pd.Dataframe(...)
data = df.gos.csv(...)
gos.Track(data).mark_bar().encode(...)
```
It might be good to dig into these methods more deeply for safer serialization of dataframes: https://github.com/altair-viz/altair/blob/master/altair/utils/data.py#L178-L217
> feat: serialize `pd.Dataframe` as csv

- .github/workflows/test.yml
- gosling/examples/between_link_pandas.py
- gosling/experimental/data.py
- gosling/sphinxext/gallery.py
Eventually, we can have a separate page like `local_data.html` (e.g., `pandas_dataframe.html`), and this example can be moved and used for that page. Wanted to share this example which I created during testing https://github.com/gosling-lang/gos/pull/63.
@manzt Is it possible to use pandas for documentation?
> feat: add a pandas example

- gosling/schema/__init__.py
- tools/generate_schema_wrapper.py
Additionally, running `tools/generate_schema_wrapper.py` currently lists the of `THEMES` in a non-deterministic order. I have edited the script to sort the themes, and change the list to set by swapping "[" with "{" brackets.
> chore: rename SCHEMA_URL_TEMPLATE -> GOSLING_URL_TEMPLATE

- gosling/examples/multiscale_lollipop_plot.py
After:
Before:
@manzt Is there a way to locally run a documentation website after making changes?
> chore: show region around BRCA2 in lollipop example

- gosling/examples/heatmap.py
Changed our heatmap data. The previous data seems to have some issues, making it very slow when loading heatmap tilesets. The rendering should be much faster now with the new data.
> fix: change heatmap example data

- gosling/data/_provider.py
Fixes the tilesets routes so they work with google colab's service worker proxy.
> feat: support colab for server

- gosling/__init__.py
- gosling/api.py
- gosling/display.py
The renderer registry is a bit overkill for the moment because there is only one rendering for gos. We can add this functionality back in the future if other renderers become available.
> refactor: remove renderer registry

- doc/getting_started/installation.rst
- gosling/data/__init__.py
- gosling/data/tests/test_provider.py
- setup.cfg
Not all users will need the server implementation, along with the those dependencies. This PR adds additional `extra_requires` to the package and dynamically will try to load the server when first used by an end user.
Adds:
```bash
pip install gosling[server] # gosling + server dependencies
pip install gosling[all] # gosling + server + gosling-widget + clodius
```
> Use extra_requires for server/optional dependencies

- doc/user_guide/API.rst
- gosling/examples/genes.py
- gosling/schema/channels.py
- tools/generate_schema_wrapper.py
Allows for `shorthand` syntax with `gos.Tooltip`. Allows,
```diff
gos.Track(genes).encode(
row=gos.Row("strand:N", domain=["+", "-"]),
color=gos.Color("strand:N", domain=["+", "-"], range=["#7585FF", "#FF8A85"]),
tooltip=[
-        gos.Tooltip(field="start", type="genomic", alt="Start Position"),
-        gos.Tooltip(field="end", type="genomic", alt="End Position"),\
-        gos.Tooltip(field="strand", type="nominal", alt="Strand"),
-        gos.Tooltip(field="name", type="nominal", alt="Name")
+        gos.Tooltip("start:G", alt="Start Position"), 
+        gos.Tooltip("end:G", alt="End Position"),
+        "strand:N", 
+        "name:N",
]
)
```
> feat: add shorthand syntax option for gos.Tooltip

- gosling/api.py
Overloads `view.save()` to also save as JSON (and throws an error if not HTML or JSON).
This should make #105 more clear with the difference between saving API and exporting objects to JSON strings.
> feat: add save('example.json') support

- gosling/api.py
- gosling/examples/circos.py
- gosling/tests/test_api.py
Defers to Gosling.js to decide defaults for `width` and `height`: https://github.com/gosling-lang/gosling.js/pull/779
> chore: use width/height defaults from gosling.js

- README.md
To fix an issue that the large GIF image makes the other contents of the README.md too small on smaller screens, like smartphones.
The repository viewed on my iPhone currently:
> chore: make GIF responsive in README.md

- gosling/display.py
- gosling/sphinxext/plot.py
A better implementation of #98.
> Rather than (painfully) dealing with global module systems in various runtimes (e.g., requirejs), this PR uses a scoped ESM import for gosling from esm.sh, an ESM only cdn.
> These URLs aren't as stable as unpkg, but the imports should work more consistently.
> refactor: use ESM import from esm.sh

- gosling/examples/area_chart.py
- gosling/examples/brushing_and_linking.py
- gosling/examples/comparative_matrices.py
- gosling/examples/corces.py
- gosling/examples/genes.py
- gosling/examples/ideograms.py
- gosling/examples/line_chart.py
- gosling/examples/multiscale_lollipop_plot.py
- gosling/examples/overview_detail.py
- gosling/examples/point_plot.py
Changed chromosome names in the examples to use `chr` prefix (e.g., `1` --> `chr1`) since the next version of Gosling will let ones use exact chromosome names (https://github.com/gosling-lang/gosling.js/pull/796).
> chore: add chr prefix to examples

- gosling/__init__.py
- gosling/api.py
- gosling/display.py
- gosling/plugin_registry.py
- gosling/renderer.py
- gosling/tests/test_plugin_registry.py
This PR adds a pluggable registry to extend rendering behavior via end user code. This will allow users to write their own renderers (or themes) in Python and override the default behavior.
Both `gos.renderers` and `gos.themes` are instances of `PluginRegistry`. 
Users can register and enable their own renderers manually. As a reminder, a renderer is any function that accepts a Gosling specification as a Python dict, and returns a Python dict in Jupyter’s [MIME Bundle format](https://jupyter-client.readthedocs.io/en/stable/messaging.html#display-data)
```python
def my_custom_renderer(spec: dict) -> dict:
...
```
```python
import gosling as gos
vis = gos.Track(...).encode(...).view()
gos.renderers.register("my-renderer", my_custom_renderer)
gos.renderers.enable("my-renderer")
vis
```
and …
> feat: add PluginRegistry with entry_points hook

- gosling/display.py
- gosling/sphinxext/plot.py
Reverts the changes from #108. Gosling.js in it's current state isn't stable enough to use esm.sh as a CDN. We need finer control over dependencies at the moment, but in the future should strive towards loading gosling with ESM.
> refactor: revert ESM imports until gosling.js is more stable

- gosling/display.py
- gosling/schema/__init__.py
- gosling/schema/core.py
- gosling/schema/gosling-schema.json
- gosling/schema/mixins.py
- tools/generate_schema_wrapper.py
~- chore: migrate build system to `hatch`~
~- run `tools/generate_schema_wrappers.py`~
~- chore: update GH Actions~
~- chore: bump higlass to v1.12~
Things seem to be working ... but some behavior is deprecated? @sehilyi the brushes in this example not longer link with the brushes on the right:
https://user-images.githubusercontent.com/24403730/223539685-f52538d2-b0c0-422c-99ef-2cc14f1dc898.mov
Note: the project now uses `hatchling` instead of `setuptools` for a build system. This is the new modern standard for python, and integrates well with the `hatch` CLI. `hatch` is like `npm`/`yarn`/`pnpm` but for python projects. You can install it globally on your system with `pipx`.
```sh
pipx install hatch
```
```sh
cd gos
hatch run test
hatch run docs
```
```sh
hatch shell # enter a virtual …
```
> feat: v0.9.28

- doc/user_guide/API.rst
- gosling/__init__.py
- gosling/data/__init__.py
- gosling/schema/__init__.py
- gosling/schema/core.py
- gosling/schema/gosling-schema.json
- pyproject.toml
- tools/generate_schema_wrapper.py
Changes:
- Bumps Gosling.js to v0.9.31
- adds `gos.bed` as a top-level API
TODO:
Need to test out some BED examples. I'm noticing that BED only seems to work for indexed BED files? If  BED file isn't indexed, should users prefer the csv loader? @sehilyi @etowahadams
> feat: Upgrade to Gosling v0.9.31

- gosling/data/__init__.py
- gosling/data/_tilesets.py
`uid` is missing on the tileset implementation when we upgraded to `servir`.
> fix: Provide uid on tileset
